stella-rium:
  turnstile: 0x4AAAAAACCiq8bKx33e5OcBArCHqWN-NLg
  jwt:
    security-key: f79082a69b39cc3e1f91c98a0b2be745
    ttl: 7200000000
    token-name: token
  bangumi:
    url: https://api.bgm.tv/
    user-agent: nnyr/stella-rium-anime-project-private
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: stella_rium_anime
    username: root
    password: 3222
  minio:
    ip: stella-rium.top
    port: 9000
    access-key: admin
    secret-key: Admin@123456
    bucket-name: sky-take-out-file